
name: Automatically create / update pull request

# run this workflow only on new feature branches, not when they're merged to main
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "main"

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create or update the pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --draft --title "My pull request" --body "Description"
          # gh_pr_up() { gh pr create $* || gh pr edit $* }
          # gh_pr_up --draft --title "My pull request" --body "Description"
